### ISSUE TITLE
Errors thrown when flat catalog is enabled

### ISSUE THREAD

**Issue by real34** [occitech/Occitech_ShopyMind#49]
We detected issues (at least for `findCategories`) when the flat catalog is enabled (due to type checking).
It is needed to check API calls with both flat catalog enabled for categories and products.

Below is a stacktrace of an error:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Incorrect collection passed for filtering categories by scope' in /path/to/app/code/local/SPM/ShopyMind/Model/Scope.php:181
Stack trace:
#0 /path/to/app/code/local/SPM/ShopyMind/Model/Scope.php(154): SPM_ShopyMind_Model_Scope->guardAgainstInvalidCategoryCollection(Object(Mage_Catalog_Model_Resource_Category_Flat_Collection))
#1 /path/to/lib/ShopymindClient/Callback.php(2032): SPM_ShopyMind_Model_Scope->restrictCategoryCollection(Object(Mage_Catalog_Model_Resource_Category_Flat_Collection))
#2 /path/to/lib/ShopymindClient/call.php(130): ShopymindClient_Callback::findCategories(false, 'fr', 'linge')
#3 {main}
  thrown in /path/to/app/code/local/SPM/ShopyMind/Model/Scope.php on line 181
```

**Comment by real34** [comment]
Has been fixed and merged in master
